stages:
  parse:
    cmd: python3 -m src.parse
    params:
      - data.raw
      - data.parsed
    deps:
      - src/parse.py
      - ${data.raw}
    outs:
      - ${data.parsed}

  clean:
    cmd: python3 -m src.clean
    params:
      - data.parsed
      - data.clean
    deps:
      - src/clean.py
      - ${data.parsed}
    outs:
      - ${data.clean}

  chunk:
    cmd: python3 -m src.chunk
    params:
      - data.clean
      - data.chunk
    deps:
      - src/chunk.py
      - ${data.clean}
    outs:
      - ${data.chunk}

  index:
    cmd: python3 -m src.index
    params:
      - data.chunk
      - data.index
    deps:
      - src/chunk.py
      - ${data.chunk}
    outs:
      - ${data.index}

  extract:
    cmd: python3 -m src.extract
    params:
      - data.index
      - data.summary
      - extraction
    deps:
      - src/extract.py
      - ${data.index}
    outs:
      - ${data.summary}
