stages:
  parse:
    cmd: python -m src.parse
    params:
      - data.raw
      - data.parsed
    deps:
      - src/parse.py
      - ${data.raw}
    outs:
      - ${data.parsed}

  clean:
    cmd: python -m src.clean
    params:
      - data.parsed
      - data.clean
    deps:
      - src/clean.py
      - ${data.parsed}
    outs:
      - ${data.clean}

