data:
  raw: "data/raw/"
  parsed: "data/parsed/"
  clean: "data/clean/"
  chunk: "data/chunk/"
chunking:
  buffer_size: 1
  percentile_threshold: 95

models:
  embed_model:
    model: "text-embedding-ada-002"
    deployment_name: "ada-3"
    api_key: "58388c947e0540da94bc64899b945ae8"
    azure_endpoint: "https://regionswedencentral.openai.azure.com/"
    api_version: "2024-02-01"

