data:
  raw: "data/raw/"
  parsed: "data/parsed/"
  clean: "data/clean/"
  chunk: "data/chunk/"
  index: "data/index/"
  summary: "data/summary/"
  mongo: "data/mongo"

chunking:
  buffer_size: 1
  percentile_threshold: 95

models:
  embed_model:
    model: "text-embedding-ada-002"
    deployment_name: "ada-3"
    api_key: "58388c947e0540da94bc64899b945ae8"
    azure_endpoint: "https://regionswedencentral.openai.azure.com/"
    api_version: "2024-02-01"
  llm:
    model: "gpt-4o"
    deployment_name: "gpt-4o-Sweden-Central"
    api_key: "58388c947e0540da94bc64899b945ae8"
    azure_endpoint: "https://regionswedencentral.openai.azure.com/"
    api_version: "2024-02-01"

extraction:
  citation_chunk_size: 1024
  kpis:
    - "revenue"
    - "cash flow"
    - "Cost of Goods Sold"
    - "COGS"
    - "Cost of Materials"
    - "Depreciation"
    - "Amortization"
    - "Purchase Price Allocation"
    - "PPA"
    - "Purchase Price Adjustmen"


  templates:
    driver: "make a short summary about the major drivers behind {company}s {kpi} change in {year}?"
    kpi: |
      - You are a professional Financial and Business analyst.
      - Your job is to find a Key Performance indicator (KPI) for {company} and format/return it
      - in the base number system (not Million/Billion) as well as retrieve the currency.\n
      - ------------------------------------
      - Example:
      - IBM's revenue for the year was $61.9 billion. -> 61900000000
      - ------------------------------------
      - find the {kpi} KPI
      - ------------------------------------
      - the output is only the formatted number and currency and nothing else!
      - if you don't find the KPI, output 'KPI not found'
      - ------------------------------------
      - Example output where KPI is found:
      - 61900000000, $
      - Example output where KPI is NOT found:
      - KPI not found
    summary: |
      - You are a professional Financial and Business analyst and you just read an incredibly long annual report of the company {company} from the year {year}.
      - You are super proud of yourself and therefore you want to summarize all the information you gathered to give your coworkers the shortest
      - and most informative summary about the annual report. Following sidenotes about the KPIs of the company you managed to gather:
      - {kpis}
      - Be as precise and short as possible with your summary, since people don't like long text and would lose interest.  
